pipeline {
    agent any
    environment {
        AWS_REGION = 'eu-west-1'
        ECR_REPOSITORY = 'frontend_repo'
        ECR_URL = "730335618715.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"
        KUBE_NAMESPACE = 'default'
        DOCKER_IMAGE = 'backend'
    }
    stages {
        // stage('Checkout') {
        //     steps {
        //         script {
        //             checkout scm
        //         }
        //     }
        // }
       
        stage('Build Docker Image') {
            steps {
                script {
                    
                    
                    DOCKER_IMAGE = "${ECR_URL}:${env.BRANCH_NAME}-${env.BUILD_NUMBER}"
                    sh "docker  build -t ${DOCKER_IMAGE} ./backend/."
                }
            }
        }
        stage('Login to ECR') {
            steps {
                
                        sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URL}"
                    
                
            }
        }
        stage('Push to ECR') {
            steps {
                script {
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'cd /var/jenkins_home/workspace/pro1-pipeline/backend && ls && chmod +x kub.sh && ./kub.sh'
                    
                    
                }
            }
        }
    }
}
